name:                haskellwebsite
version:             0.1.0.0
github:              "githubuser/haskellwebsite"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/haskellwebsite#readme>

dependencies:
- base >= 4.7 && < 5
- Spock
# - clay
- blaze-html
- blaze-bootstrap
# - JMacro
- fay
- aeson
# - happstack-server
- text
- hlib
- transformers
- filepath
- unix-compat
- wai-middleware-static
- users
- unordered-containers
- base64-bytestring
- bytestring
- directory
- lens

library:
  source-dirs: src

executables:
  haskellwebsite:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellwebsite

tests:
  haskellwebsite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskellwebsite
